### ISSUE TITLE
Error in MasterItem Endpoint

### ISSUE THREAD

**Issue by codemickeycode** [cr8ivecodesmith/marketsnitch#32]
AssertionError at /api/v1/masterlist/masteritem.json
'MasterItemLAPI' should either include a `queryset` attribute, or override the `get_queryset()` method.

Request Method: GET
Request URL: http://127.0.0.1:8000/api/v1/masterlist/masteritem.json

**Comment by codemickeycode** [comment]
Django rest framework error

**Comment by cr8ivecodesmith** [comment]
Fixed by https://github.com/cr8ivecodesmith/marketsnitch/pull/40
