### ISSUE TITLE
Error in MasterItem Datatable

### ISSUE THREAD

**Issue by codemickeycode** [cr8ivecodesmith/marketsnitch#33]
TypeError at /api/v1/masterlist/datatable
    __init__() got an unexpected keyword argument 'mimetype'
    Request Method: GET
    Request URL: http://127.0.0.1:8000/api/v1/masterlist/datatable?sEcho=1&iColumns=5&sColumns=%2C%2C%2C%2C&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=true&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&sSearch=&bRegex=false&iSortCol_0=0&sSortDir_0=asc&iSortingCols=1&_=1428174825473

**Comment by codemickeycode** [comment]
api bug

**Comment by cr8ivecodesmith** [comment]
Temp fix:
Comment out `line 214 `views.py` in

**Comment by cr8ivecodesmith** [comment]
Superseded by https://github.com/cr8ivecodesmith/marketsnitch/issues/41
