### ISSUE TITLE
Philgeps BidInformation Endpoint always returns 504 error

### ISSUE THREAD

**Issue by cr8ivecodesmith** [cr8ivecodesmith/marketsnitch#34]
Since April 04, 2015 the BidInformation endpoint in their website return error 504.

    http://data.gov.ph/catalogue/dataset/philgeps-public-data/resource/9c74991c-a5e6-4489-8413-c20a8a181d90

I think we just need to raise this issue to PhilGeps/OpenDataPhils teams.

**Comment by codemickeycode** [comment]
No feedback regarding this yet. For the meantime, let's just use the old CSV we downloaded during the hackathon.

**Comment by cr8ivecodesmith** [comment]
I think we can close this issue now since we've found out that their API is working.
